<!DOCTYPE html>
<%@ page language="java" contentType="text/html; charset= UTF-8" pageEncoding="UTF-8"%>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, user-scalable=no">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=yes, target-densitydpi=medium-dpi" />
<meta http-equiv="Cache-Control" content="no-cache">
<meta http-equiv="Pragma" content="no-cache">

<meta name='Title' content='인적자원관리 전문IT기업 - NEWZEN P&P'>
<meta name="keywords" content="페이롤, 급여대행, 급여아웃소싱, 연말정산대행, 4대보험대행, 전자문서, 전자계약, 고용보험대행, 산재보험대행, 뉴젠P&P" />
<meta name="description" content="인적자원관리 전문IT기업 뉴젠P&P. 나눔페이롤, K-FORM, e-공단을 통해 4대보험, 연말정산, 급여관리 등을 대행서비스 진행">
<meta property="og:title" content="인적자원관리 전문IT기업 - NEWZEN P&P">
<meta property="og:description" content="정부 비대면 바우처를 신청하세요.지금 신청하면 90%할인된 가격에 만나실 수 있습니다.">
<meta property="og:image" content="img/site.jpg">
<title>인적자원관리 전문IT기업 - NEWZEN P&P</title>
<script src="/voucher/js/lib/jquery-3.3.1.min.js"></script>
<script type='text/javascript' src="/js/common.js"></script>
<link href='/voucher/css/voucher.css' type='text/css' rel='stylesheet'>

<style>
	.head_title {text-align: center; font-weight: 600; font-size:10px; text-shadow: 2px 2px 2px rgb(0 0 0 / 40%); padding-top: 70px;
</style>

<script>
	$(document).ready(function(){

	});
</script>
			
</head>
<body>
	<div style="text-align: center;">
		<!-- Image Map Generated by http://www.image-map.net/ -->
		<img src="/images/memberJoin_kclep.png" usemap="#image-map">

		<map name="image-map">
			<area target="_blank" alt="memberJoin" title="memberJoin" href="https://ieumsign.co.kr/menu/goMemberJoin2.do?menuType=6&funnel=600" coords="382,344,713,456" shape="rect">
		</map>
	</div>
</body>
</html>