package com.ezsign.feb.worker.vo;

import lombok.Data;

@Data
public class YE700VO {

    private String 계약ID;
    private String 사용자ID;
    private String 작업자ID;
    private String 일련번호;

    private String 세액공제구분코드;

    private long 총급여 = 0;
    private long 근로소득공제 = 0;
    private long 근로소득금액 = 0;
    private long 기본공제_본인 = 0;
    private long 기본공제_배우자 = 0;
    private long 부양가족_인원수 = 0;
    private long 기본공제_부양가족 = 0;
    private long 경로우대_인원수 = 0;
    private long 추가공제_경로우대 = 0;
    private long 장애인_인원수 = 0;
    private long 추가공제_장애인 = 0;
    private long 추가공제_부녀자 = 0;
    private long 추가공제_한부모 = 0;
    private long 인적공제_계 = 0;
    private long 연금보험_국민연금 = 0;
    private long 연금보험_국민연금_공제대상금액 = 0;    
    private long 연금보험_공무원연금 = 0;    
    private long 연금보험_공무원연금_공제대상금액 = 0;
    private long 연금보험_군인연금 = 0;
    private long 연금보험_군인연금_공제대상금액 = 0;
    private long 연금보험_사립학교 = 0;
    private long 연금보험_사립학교_공제대상금액 = 0;
    private long 연금보험_별정우체국 = 0;
    private long 연금보험_별정우체국_공제대상금액 = 0;
    private long 연금보험_계 = 0;
    private long 특별소득_건강보험 = 0;
    private long 특별소득_건강보험_공제대상금액 = 0;
    private long 특별소득_고용보험 = 0;
    private long 특별소득_고용보험_공제대상금액 = 0;
    private long 특별소득_주택원리금_대출기관 = 0;
    private long 특별소득_주택원리금_거주자 = 0;
    private long 특별소득_장기주택_2011년이전_15년미만 = 0;
    private long 특별소득_장기주택_2011년이전_15년29년 = 0;
    private long 특별소득_장기주택_2011년이전_30년이상 = 0;
    private long 특별소득_장기주택_2012년이후_고정이거나비거치 = 0;
    private long 특별소득_장기주택_2012년이후_그밖에 = 0;
    private long 특별소득_장기주택_2015년이후_15년이상_고정이면서비거치 = 0;
    private long 특별소득_장기주택_2015년이후_15년이상_고정이거나비거치 = 0;
    private long 특별소득_장기주택_2015년이후_15년이상_그밖에 = 0;
    private long 특별소득_장기주택_2015년이후_10년15년_고정이거나비거치 = 0;
    private long 특별소득_기부금_이월분 = 0;
    private long 특별소득_계 = 0;
    private long 차감소득금액 = 0;
    private long 그밖에소득공제_개인연금 = 0;
    private long 그밖에소득공제_소기업소상공인 = 0;
    private long 그밖에소득공제_주택마련_청약저축 = 0;
    private long 그밖에소득공제_주택마련_주택청약 = 0;
    private long 그밖에소득공제_주택마련_근로자주택마련 = 0;
    private long 그밖에소득공제_투자조합출자 = 0;
    private long 그밖의소득공제_투자조합출자_벤처_공제액_2016년 = 0;
    private long 그밖의소득공제_투자조합출자_벤처_공제액_2017년 = 0;
    private long 그밖의소득공제_투자조합출자_벤처_공제액_2018년 = 0;
    private long 그밖에소득공제_투자조합출자_조합 = 0;
    private long 그밖에소득공제_신용카드등 = 0;
    private long 그밖에소득공제_우리사주조합 = 0;
    private long 그밖에소득공제_고용유지근로자 = 0;
    private long 그밖에소득공제_장기집합투자 = 0;
    private long 그밖에소득공제_계 = 0;
    private long 소득공제종합한도초과액 = 0;
    private long 종합소득과세표준 = 0;
    private long 산출세액 = 0;
    private long 세액감면_소득세법 = 0;
    private long 세액감면_조세특례52제외 = 0;
    private long 세액감면_조세특례30조 = 0;
    private long 세액감면_조세특례30조_100 = 0;
    private long 세액감면_조세특례30조_50 = 0;
    private long 세액감면_조세특례30조_70 = 0;
    private long 세액감면_조세특례30조_90 = 0;
    private long 세액감면_조세조약 = 0;
    private long 세액감면_계 = 0;
    private long 세액공제_근로소득 = 0;
    private long 자녀_인원수 = 0;
    private long 세액공제_자녀 = 0;
    private long 세액공제_6세이하_인원수 = 0;
    private long 세액공제_6세이하 = 0;
    private long 출산입양_인원수 = 0;
    private long 세액공제_출산입양 = 0;
    private long 세액공제_자녀세액공제_계 = 0;
    private long 세액공제_연금계좌_과학기술_공제대상금액 = 0;
    private long 세액공제_연금계좌_과학기술_세액공제액 = 0;
    private long 세액공제_연금계좌_퇴직연금_공제대상금액 = 0;
    private long 세액공제_연금계좌_퇴직연금_세액공제액 = 0;
    private long 세액공제_연금계좌_연금저축_공제대상금액 = 0;
    private long 세액공제_연금계좌_연금저축_세액공제액 = 0;
    private long 세액공제_연금계좌_계 = 0;
    private long 특별세액_보험료_보장성_공제대상금액 = 0;
    private long 특별세액_보험료_보장성_세액공제액 = 0;
    private long 특별세액_보험료_장애인전용_공제대상금액 = 0;
    private long 특별세액_보험료_장애인전용_세액공제액 = 0;
    private long 특별세액_의료비_공제대상금액 = 0;
    private long 특별세액_의료비_세액공제액 = 0;
    private long 특별세액_교육비_공제대상금액 = 0;
    private long 특별세액_교육비_세액공제액 = 0;
    private long 특별세액_기부금_정치자금_10만이하_공제대상금액 = 0;
    private long 특별세액_기부금_정치자금_10만이하_세액공제액 = 0;
    private long 특별세액_기부금_정치자금_10만초과_공제대상금액 = 0;
    private long 특별세액_기부금_정치자금_10만초과_세액공제액 = 0;
    private long 특별세액_기부금_법정_공제대상금액 = 0;
    private long 특별세액_기부금_법정_세액공제액 = 0;
    private long 특별세액_기부금_우리사주_공제대상금액 = 0;
    private long 특별세액_기부금_우리사주_세액공제액 = 0;
    private long 특별세액_기부금_지정_종교외_공제대상금액 = 0;
    private long 특별세액_기부금_지정_종교외_세액공제액 = 0;
    private long 특별세액_기부금_지정_종교_공제대상금액 = 0;
    private long 특별세액_기부금_지정_종교_세액공제액 = 0;
    private long 특별세액_계 = 0;
    private long 특별세액_표준세액공제 = 0;
    private long 세액공제_납세조합공제 = 0;
    private long 세액공제_주택차입금 = 0;
    private long 세액공제_외국납부 = 0;
    private long 세액공제_월세액_공제대상금액 = 0;
    private long 세액공제_월세액_세액공제액 = 0;
    private long 세액공제_계 = 0;
    private long 결정세액_소득세 = 0;
    private long 결정세액_지방소득세 = 0;
    private long 결정세액_농어촌특별세 = 0;

    private String 종1_사업자번호;
    private long 종1_소득세 = 0;
    private long 종1_지방소득세 = 0;
    private long 종1_농어촌특별세 = 0;
    private String 종2_사업자번호;
    private long 종2_소득세 = 0;
    private long 종2_지방소득세 = 0;
    private long 종2_농어촌특별세 = 0;
    private String 종3_사업자번호;
    private long 종3_소득세 = 0;
    private long 종3_지방소득세 = 0;
    private long 종3_농어촌특별세 = 0;

    private long 주근무지_소득세 = 0;
    private long 주근무지_지방소득세 = 0;
    private long 주근무지_농어촌특별세 = 0;
    private long 종근무지_소득세 = 0;
    private long 종근무지_지방소득세 = 0;
    private long 종근무지_농어촌특별세 = 0;
    private long 납부특례_소득세 = 0;
    private long 납부특례_지방소득세 = 0;
    private long 납부특례_농어촌특별세 = 0;

    private long 차감징수_소득세 = 0;
    private long 차감징수_지방소득세 = 0;
    private long 차감징수_농어촌특별세 = 0;

    private String 사용여부;
    private String 등록일시;
    private String 수정일시;
    
    private String bizId;
    private String febYear;
    private String empName;
    private String empNo;
    private String 사업장ID;
    private String 사업장명;
    private String 부서ID;
    private String 부서명;
    private String 소득총급여;
    private String 차감징수소득세;
    private String 차감징수지방소득세;
    private String 납부환급세액;
    private String 근무상태;
    private String 마감상태;
    private String 진행상태코드;
    private String 마감;
    private String 결정세액;
    
    private String sortName;
    private String sortOrder;
    private int startPage;
    private int endPage;
}
